
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: 🧑🏻‍💻 checkout source code
        uses: actions/checkout@v2.3.4

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: 😎 Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '18.x'

      # https://github.com/marketplace/actions/yarn-install-cache
      - name: 🚀 yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: 🕸 install dependencies on ubuntu
        run: yarn install

      - name: 🏢 build
        run: yarn build

      - name: 👊🏻 deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.T_GITHUB_TOKEN }}
        with:
          email: javaparknet@gmail.com
          build_dir: public
          branch: main